version: "2"
engines:
  phpmd:
    enabled: true
    config:
      rulesets: "unusedcode,codesize,naming,design,controversial,cleancode,phpmd.xml"
  phan:
    enabled: true
  phpcodesniffer:
    enabled: true
  sonar-php:
    enabled: true
exclude_patterns:
- "tests/"
- "src/Cmixin/HolidayNames/"
- "src/Cmixin/Holidays/"
- "src/Cmixin/BusinessDay/Calendar/LunarCalendar.php"
