version: "2"
engines:
  phpmd:
    enabled: true
    config:
      rulesets: "unusedcode,codesize,naming,design,controversial,phpmd.xml"
  phan:
    enabled: true
    config:
      ignore-undeclared: true
  phpcodesniffer:
    enabled: true
  sonar-php:
    enabled: true
exclude_patterns:
- "tests/"
- "src/Cmixin/HolidayNames/"
- "src/Cmixin/Holidays/"
- "src/Cmixin/BusinessDay/Calendar/LunarCalendar.php"
- "src/Types/"
- "src/_ide_business_day_instantiated.php"
- "src/_ide_business_day_static.php"
